### PR TITLE
Make plugin compatible with module loaders

### PR DESCRIPTION
**Pull request by jonscottclark**
Duplicate of #85 by @metaraine — minified version included + some comments.

**plz plz merge**.

Believe me, many other people need this. We don't have time for browserify-shim, etc. in order to get your plugin working with browserify bundles.

### CODE REVIEW

**Comment by liabru** [comment]
Sorry for the delay on this guys!

**Comment by jonscottclark** [comment]
No worries, sorry if I came off sounding harsh! Thanks for your work on this, @liabru , it's much appreciated.

**Comment by connorjburton** [comment]
This doesn't seem to have been pushed up to NPM?

Where it is most useful ;)

**Comment by jonscottclark** [comment]
https://www.npmjs.com/package/jquery-match-height

**Comment by connorjburton** [comment]
Sorry, the latest version doesn't seem to have. The fix you PR'd.

**Comment by jonscottclark** [comment]
Ohh, I see! True.. needs a version bump and release, @liabru

**Pull request merged**
